In [5]:
# 1. Usando NumPy, crea un Pandas DataFrame con cinco filas y tres columms:
from numpy import random
import pandas as pd

random.randint(100, size=(3, 5))
data_array = random.randint(100, size=(5, 3))

print("La matriz de datos NumPy es:")
print(data_array)

print("")

data_df = pd.DataFrame(data_array)
print("El DataFrame generado a partir de la matriz NumPy es:")
print(data_df)

La matriz de datos NumPy es:
[[75 42 14]
 [79 62 86]
 [14 81 89]
 [81 78 38]
 [61  5  2]]

El DataFrame generado a partir de la matriz NumPy es:
    0   1   2
0  75  42  14
1  79  62  86
2  14  81  89
3  81  78  38
4  61   5   2


In [4]:
#3. Cree un segundo DataFrame como el anterior con cinco filas y tres columnas, estableciendo las etiquetas 
#de fila en los nombres de las cinco ciudades principales de EE. UU. y las etiquetas de columna 
#en los primeros tres meses del año.
import pandas as pd
datos={'enero': [1, 2, 4, 7, 8], 'febrero': [3, 5, 6, 1, 7], 'marzo': [5, 0, 7, 2, 3]}

indices=['New York', 'California', 'Illinois', 'Texas', 'Arizona']
df = pd.DataFrame(data=datos, index=indices)
print(df)

            enero  febrero  marzo
New York        1        3      5
California      2        5      0
Illinois        4        6      7
Texas           7        1      2
Arizona         8        7      3


In [38]:
#4.Suponiendo que las funciones para hacerlo tienen "datos" en el nombre, ¿cómo podría ubicarlas? 
[x for x in dir(sb) if "data" in x]

sb.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'taxis',
 'tips',
 'titanic']

In [2]:

%pip install seaborn


You should consider upgrading via the 'C:\Users\HP\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


  Using cached seaborn-0.11.2-py3-none-any.whl (292 kB)
Note: you may need to restart the kernel to use updated packages.


In [25]:
#5. Los datos del hogar de Zillow están disponibles en esta URL: 
#https://files.zillowstatic.com/research/public_csvs/zhvi/Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv
df_homes = pd.read_csv("https://files.zillowstatic.com/research/public_csvs/zhvi/Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv")


In [51]:
#6. Guarde el DataFrame, df_homes, en un archivo CSV local, "zillow_home_data.csv".
df_homes.to_csv('zillow_home_data.csv')

In [52]:
#7. Vuelva a cargar zillow_home_data.csv en un nuevo Dataframe, df_homes_2
df_homes_2 = pd.read_csv('zillow_home_data.csv')

In [53]:
#8. Compare las dimensiones de los dos DataFrames, df_homes y df_homes_2. ¿Son iguales? Si no es así, ¿cómo puedes solucionarlo?
print(df_homes.shape)
print(df_homes_2.shape)
print(df_homes.shape == df_homes_2.shape)

(908, 275)
(908, 276)
False


In [14]:
#11. Usando Seaborn, obtenga un conjunto de datos sobre pingüinos en un marco de datos llamado "df_penguins". 
#Tenga en cuenta que debido a que todas las siguientes preguntas dependen de este ejemplo, proporcionaremos 
#la solución aquí para que nadie se quede atascado:
import pandas as pd
import numpy as np
import seaborn as sb
df_penguins = sb.load_dataset('penguins')

print(df_penguins)


    species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2     

7

In [18]:
#12. Escriba el código para mostrar el número de filas y columnas en df_penguins
df=df_penguins
print('el numero de columnas es:')
print(len(df.columns))
print('el numero de filas es:')
print(len(df.index))

el numero de columnas es:
7
el numero de filas es:
344


In [19]:
#13. ¿Cómo podrías mostrar las primeras filas de df_penguins?
df.iloc[0:3]

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female

In [40]:
#14. ¿Cómo puedes devolver las especies únicas de pingüinos de df_penguins? ¿Cuántas especies únicas hay?
species = df_penguins["species"].copy()
unique = species.fillna(0)
unique = unique.drop_duplicates()
nrows = unique.shape[0]
print(unique)
print(f"existen {nrows} unicas especies, {list(unique.values)}.")

0         Adelie
152    Chinstrap
220       Gentoo
Name: species, dtype: object
existen 3 unicas especies, ['Adelie', 'Chinstrap', 'Gentoo'].


In [31]:
#15. ¿Qué función podemos usar para soltar las filas que tienen datos faltantes?
df_penguins.dropna()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
4    Adelie  Torgersen            36.7           19.3              193.0   
5    Adelie  Torgersen            39.3           20.6              190.0   
..      ...        ...             ...            ...                ...   
338  Gentoo     Biscoe            47.2           13.7              214.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
4         3450.0  Female  
5         3650.0    Male  
..           ...     ...  
338       4925.0  Female  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[333 rows x 7 columns]

In [32]:
#17. ¿Cómo podemos anular el valor predeterminado?
df_penguins.dropna(inplace=True)

In [33]:
#18. Cree un nuevo DataFrame, df_penguins_full, con los datos que faltan eliminados.
df_penguins_full = df_penguins.dropna()
df_penguins_full.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [34]:
#19. ¿Cuál es la longitud media de la factura de un pingüino, en milímetros, en este conjunto de datos (df_full)?
df_penguins_full['bill_length_mm'].mean()

43.99279279279279

In [42]:
#20. ¿Cuál de las siguientes opciones está más fuertemente correlacionada con la longitud del pico? 
#a) ¿Masa corporal? b) ¿Longitud de la aleta? c) ¿Profundidad de la factura? Muestre cómo llegó a la respuesta.
print(df_penguins_full['bill_length_mm'].corr(df_penguins_full['body_mass_g']))
print(df_penguins_full['bill_length_mm'].corr(df_penguins_full['flipper_length_mm']))
print(df_penguins_full['bill_length_mm'].corr(df_penguins_full['bill_depth_mm']))

0.5894511101769488
0.6530956386670861
-0.2286256359130292


In [36]:
#21. ¿Cómo podría mostrar la longitud media de la aleta, agrupada por especies?
df_penguins_full.groupby('species').mean()['flipper_length_mm']


species
Adelie       190.102740
Chinstrap    195.823529
Gentoo       217.235294
Name: flipper_length_mm, dtype: float64

In [37]:
#22. ¿Qué dos especies tienen el peso medio más similar? Muestre cómo llegó a la respuesta.
df_penguins_full.groupby('species').mean()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
species                                                                 
Adelie          38.823973      18.347260         190.102740  3706.164384
Chinstrap       48.833824      18.420588         195.823529  3733.088235
Gentoo          47.568067      14.996639         217.235294  5092.436975

In [43]:
#23  ¿Qué dos especies tienen el peso medio más similar? Muestre cómo llegó a la respuesta.
df_penguins_full.groupby('species').mean()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
species                                                                 
Adelie          38.823973      18.347260         190.102740  3706.164384
Chinstrap       48.833824      18.420588         195.823529  3733.088235
Gentoo          47.568067      14.996639         217.235294  5092.436975

In [44]:
# 24. ¿Cómo se pueden ordenar las filas por longitud de la factura?
df_penguins.sort_values('bill_length_mm')

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
142     Adelie      Dream            32.1           15.5              188.0   
98      Adelie      Dream            33.1           16.1              178.0   
70      Adelie  Torgersen            33.5           19.0              190.0   
92      Adelie      Dream            34.0           17.1              185.0   
18      Adelie  Torgersen            34.4           18.4              184.0   
..         ...        ...             ...            ...                ...   
335     Gentoo     Biscoe            55.1           16.0              230.0   
215  Chinstrap      Dream            55.8           19.8              207.0   
321     Gentoo     Biscoe            55.9           17.0              228.0   
169  Chinstrap      Dream            58.0           17.8              181.0   
253     Gentoo     Biscoe            59.6           17.0              230.0   

     body_mass_g     sex  
142       3050.0  Female  
98        2900.0  Female  
70        3600.0  Female  
92        3400.0  Female  
18        3325.0  Female  
..           ...     ...  
335       5850.0    Male  
215       4000.0    Male  
321       5600.0    Male  
169       3700.0  Female  
253       6050.0    Male  

[333 rows x 7 columns]

In [45]:
#25. ¿Cómo podría ejecutar el mismo tipo en orden descendente?
df_penguins.sort_values(['bill_length_mm'], ascending=False)

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
253     Gentoo     Biscoe            59.6           17.0              230.0   
169  Chinstrap      Dream            58.0           17.8              181.0   
321     Gentoo     Biscoe            55.9           17.0              228.0   
215  Chinstrap      Dream            55.8           19.8              207.0   
335     Gentoo     Biscoe            55.1           16.0              230.0   
..         ...        ...             ...            ...                ...   
18      Adelie  Torgersen            34.4           18.4              184.0   
92      Adelie      Dream            34.0           17.1              185.0   
70      Adelie  Torgersen            33.5           19.0              190.0   
98      Adelie      Dream            33.1           16.1              178.0   
142     Adelie      Dream            32.1           15.5              188.0   

     body_mass_g     sex  
253       6050.0    Male  
169       3700.0  Female  
321       5600.0    Male  
215       4000.0    Male  
335       5850.0    Male  
..           ...     ...  
18        3325.0  Female  
92        3400.0  Female  
70        3600.0  Female  
98        2900.0  Female  
142       3050.0  Female  

[333 rows x 7 columns]

In [46]:
#26. ¿Cómo podrías ordenar por especie primero, luego por masa corporal?
df_penguins.sort_values(['species', 'body_mass_g'])

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
58   Adelie     Biscoe            36.5           16.6              181.0   
64   Adelie     Biscoe            36.4           17.1              184.0   
54   Adelie     Biscoe            34.5           18.1              187.0   
98   Adelie      Dream            33.1           16.1              178.0   
116  Adelie  Torgersen            38.6           17.0              188.0   
..      ...        ...             ...            ...                ...   
331  Gentoo     Biscoe            49.8           15.9              229.0   
297  Gentoo     Biscoe            51.1           16.3              220.0   
337  Gentoo     Biscoe            48.8           16.2              222.0   
253  Gentoo     Biscoe            59.6           17.0              230.0   
237  Gentoo     Biscoe            49.2           15.2              221.0   

     body_mass_g     sex  
58        2850.0  Female  
64        2850.0  Female  
54        2900.0  Female  
98        2900.0  Female  
116       2900.0  Female  
..           ...     ...  
331       5950.0    Male  
297       6000.0    Male  
337       6000.0    Male  
253       6050.0    Male  
237       6300.0    Male  

[333 rows x 7 columns]